"""Freeze a small Mol-JEPA reference, in its own process, for `verify_jepa_embed.py`.

The counterpart of `dump_reference_embeddings.py` on the MiniMol side, and it exists for the
same reason: a verification that only compares the cache against the model *as loaded right
now* proves the cache was written correctly and nothing else. It cannot notice that the
model itself changed -- and this model is fetched from the Hub with `trust_remote_code=True`,
so its code and its weights can both move under us between runs.

A frozen fixture turns that into a failing check. It records the SMILES, both output
tensors, and the revision that produced them, so a later run that resolves a different
revision, or the same revision behaving differently, fails loudly instead of quietly
producing a slightly different encoder.

Written by loading the model the plain documented way -- `AutoModel` + `model(smiles_list)`
-- deliberately *not* through `jepa_embed.py`. A fixture generated by the code it is meant
to check would agree with it by construction.

Usage:
    python src/dump_jepa_reference.py
    python src/dump_jepa_reference.py -n 64 -o data/reference/moljepa_v1_ref64
"""

import argparse
import json
import os
import platform
import sys
from pathlib import Path

# Before torch -- cuBLAS reads it at init. See DETERMINISM in src/jepa_embed.py.
os.environ.setdefault("CUBLAS_WORKSPACE_CONFIG", ":4096:8")

import numpy as np
import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parent))
from jepa_embed import HF_REPO, HF_REVISION  # noqa: E402  (one pin, not two)


def parse_args(argv=None):
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("-i", "--input", type=Path, default=Path("data/ampc_subset_331k.csv"))
    p.add_argument("-n", type=int, default=64, help="molecules to freeze")
    p.add_argument("-o", "--out", type=Path,
                   default=Path("data/reference/moljepa_v1_ref64"),
                   help="stem; .npz and .json are written")
    p.add_argument("--repo", default=HF_REPO)
    p.add_argument("--revision", default=HF_REVISION)
    p.add_argument("--device", default="cpu",
                   help="cpu by default: it is bit-exact without needing "
                        "use_deterministic_algorithms, so the fixture does not depend on "
                        "that flag being set correctly by whoever regenerates it.")
    return p.parse_args(argv)


def main(argv=None):
    args = parse_args(argv)
    import torch
    from transformers import AutoModel

    smiles = pd.read_csv(args.input, usecols=["SMILES"])["SMILES"].tolist()[:args.n]
    print(f"{len(smiles)} molecules from {args.input} (first {args.n} rows, in file order)")

    model = AutoModel.from_pretrained(args.repo, revision=args.revision,
                                      trust_remote_code=True).eval().to(args.device)
    with torch.no_grad():
        out = model(smiles)
        again = model(smiles)

    emb = out.embeddings.float().cpu().numpy()
    proj = torch.cat([out.cls.unsqueeze(1), out.predictions], dim=1).float().cpu().numpy()
    repeat_maxdiff = max(
        (out.embeddings - again.embeddings).abs().max().item(),
        (out.cls - again.cls).abs().max().item(),
        (out.predictions - again.predictions).abs().max().item(),
    )
    print(f"embeddings {emb.shape}  projected {proj.shape}  "
          f"repeat max|delta| = {repeat_maxdiff:.3e} on {args.device}")

    try:
        from huggingface_hub import HfApi
        resolved = HfApi().model_info(args.repo, revision=args.revision).sha
    except Exception as exc:
        resolved = None
        print(f"  ! could not resolve revision ({exc})")

    core = model.model
    token_names = ["cls"] + [m["name"] for m in core.modalities_spec]

    args.out.parent.mkdir(parents=True, exist_ok=True)
    npz, meta_path = args.out.with_suffix(".npz"), args.out.with_suffix(".json")
    np.savez(npz, embeddings=emb, projected=proj)
    meta_path.write_text(json.dumps({
        "script": "src/dump_jepa_reference.py",
        "argv": sys.argv,
        "smiles": smiles,
        "input": str(args.input),
        "hf_repo": args.repo,
        "hf_revision_requested": args.revision,
        "hf_revision": resolved,
        "token_names": token_names,
        "n_parameters": sum(p.numel() for p in model.parameters()),
        "device": args.device,
        "repeat_maxdiff": repeat_maxdiff,
        "shapes": {"embeddings": list(emb.shape), "projected": list(proj.shape)},
        "versions": {"python": platform.python_version(), "torch": torch.__version__},
        "host": platform.node(),
    }, indent=2) + "\n")
    print(f"wrote {npz} and {meta_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
